// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const configuredUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];
const datasourceUrl = configuredUrl?.startsWith("file:")
  ? configuredUrl
  : "file:./prisma/dev.db";

process.env["DATABASE_URL"] = datasourceUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
